name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza con la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Usa una versión más reciente de Node.js

    - name: Build and Deploy
      run: |
        mkdir public
        cp -r * public/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
