name: GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza con la rama que estés usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v1

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Rama en la que se desplegará
        folder: /         # Carpeta que contiene el sitio web

    - name: GitHub Pages build status
      uses: actions/github-script@v3
      with:
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'github/pages-build',
            description: 'Pages has been built and deployed successfully',
            target_url: `https://${context.repo.owner}.github.io/${context.repo.repo}/`,
          })
